[package]
name = "aranet"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
btleplug = "0.11.8"
futures = "0.3.31"
serde = "1.0.219"
tokio = { version = "1.45.0", features = ["full"] }
toml = "0.8.22"
